// Code generated by mockery v2.52.2. DO NOT EDIT.

package mocks

import (
	eventbus "github.com/seb7887/gofw/eventbus"
	mock "github.com/stretchr/testify/mock"
)

// Bus is an autogenerated mock type for the Bus type
type Bus[T eventbus.Message] struct {
	mock.Mock
}

type Bus_Expecter[T eventbus.Message] struct {
	mock *mock.Mock
}

func (_m *Bus[T]) EXPECT() *Bus_Expecter[T] {
	return &Bus_Expecter[T]{mock: &_m.Mock}
}

// Publish provides a mock function with given fields: topic, msg
func (_m *Bus[T]) Publish(topic string, msg eventbus.Message) error {
	ret := _m.Called(topic, msg)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, eventbus.Message) error); ok {
		r0 = rf(topic, msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Bus_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type Bus_Publish_Call[T eventbus.Message] struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - topic string
//   - msg eventbus.Message
func (_e *Bus_Expecter[T]) Publish(topic interface{}, msg interface{}) *Bus_Publish_Call[T] {
	return &Bus_Publish_Call[T]{Call: _e.mock.On("Publish", topic, msg)}
}

func (_c *Bus_Publish_Call[T]) Run(run func(topic string, msg eventbus.Message)) *Bus_Publish_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(eventbus.Message))
	})
	return _c
}

func (_c *Bus_Publish_Call[T]) Return(_a0 error) *Bus_Publish_Call[T] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Bus_Publish_Call[T]) RunAndReturn(run func(string, eventbus.Message) error) *Bus_Publish_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Subscribe provides a mock function with given fields: topic, handler
func (_m *Bus[T]) Subscribe(topic string, handler eventbus.MessageReceiver) {
	_m.Called(topic, handler)
}

// Bus_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type Bus_Subscribe_Call[T eventbus.Message] struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - topic string
//   - handler eventbus.MessageReceiver
func (_e *Bus_Expecter[T]) Subscribe(topic interface{}, handler interface{}) *Bus_Subscribe_Call[T] {
	return &Bus_Subscribe_Call[T]{Call: _e.mock.On("Subscribe", topic, handler)}
}

func (_c *Bus_Subscribe_Call[T]) Run(run func(topic string, handler eventbus.MessageReceiver)) *Bus_Subscribe_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(eventbus.MessageReceiver))
	})
	return _c
}

func (_c *Bus_Subscribe_Call[T]) Return() *Bus_Subscribe_Call[T] {
	_c.Call.Return()
	return _c
}

func (_c *Bus_Subscribe_Call[T]) RunAndReturn(run func(string, eventbus.MessageReceiver)) *Bus_Subscribe_Call[T] {
	_c.Run(run)
	return _c
}

// NewBus creates a new instance of Bus. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBus[T eventbus.Message](t interface {
	mock.TestingT
	Cleanup(func())
}) *Bus[T] {
	mock := &Bus[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
